# Generated by Django 5.2.8 on 2025-11-20 23:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Carga')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_cargados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Carga')),
            ],
            options={
                'verbose_name': 'Archivo Masivo',
                'verbose_name_plural': 'Archivos Masivos',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Ejecuta')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Factor')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
