# Generated by Django 5.2.8 on 2025-11-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='factor',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5, verbose_name='Factor'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='monto',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Monto (CLP)'),
        ),
    ]
