# Generated by Django 5.2.8 on 2025-11-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_alter_calificacion_factor_alter_calificacion_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='factor',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='tipo_movimiento',
            field=models.CharField(choices=[('abono', 'ABONO'), ('cargo', 'CARGO')], default='abono', max_length=10, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto (CLP)'),
        ),
    ]
