# Generated by Django 5.2.8 on 2025-11-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_remove_calificacion_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='tipo_movimiento',
            field=models.CharField(choices=[('abono', 'ABONO'), ('cargo', 'CARGO'), ('pago', 'PAGO'), ('reembolso', 'REEMBOLSO')], default='abono', max_length=10, verbose_name='Tipo de Movimiento'),
        ),
    ]
